name: Deployment

on:
  push:
    branches: [ "master", "next" ]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.11.0
      uses: actions/setup-node@v3
      with:
        node-version: 20.11.0

    - name: Type Check
      run: |
        npm install --include=dev
        npm run check

  build:
    needs: typecheck
    if: success()
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.11.0
      uses: actions/setup-node@v3
      with:
        node-version: 20.11.0

    - name: Run Build
      run: |
        npm install --include=dev
        npm run build

    # Log in to the GitHub Container Registry (GHCR)
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build Docker image
      if: ${{ github.ref_name == 'master' }}
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest .
        
    - name: Build Docker image
      if: ${{ github.ref_name == 'next' }}
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:next .

    # Push the Docker image to GitHub Container Registry
    - name: Push Docker image to GHCR
      if: ${{ github.ref_name == 'master' }}
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

    # Push the Docker image to GitHub Container Registry
    - name: Push Docker image to GHCR
      if: ${{ github.ref_name == 'next' }}
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:next
        
